//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Localization.PushNotifications {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_sq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_sq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Localization.PushNotifications.Strings-sq", typeof(Strings_sq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key përdoret për tu lidhur me SendGrid. (Api Key nuk është i njëjtë me username dhe password që përdoret për tu loguar tek SendGrid).
        /// </summary>
        public static string ApiKey_Description {
            get {
                return ResourceManager.GetString("ApiKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kliko gjurmimin .
        /// </summary>
        public static string ClickTracking {
            get {
                return ResourceManager.GetString("ClickTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivizon funksionin e gjurmimit së SendGrid.
        /// </summary>
        public static string ClickTracking_Description {
            get {
                return ResourceManager.GetString("ClickTracking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivizuar.
        /// </summary>
        public static string ClickTracking_Prompt {
            get {
                return ResourceManager.GetString("ClickTracking_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsilidoni njoftimet.
        /// </summary>
        public static string ConsolidateNotifications {
            get {
                return ResourceManager.GetString("ConsolidateNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsolidimi lejon që njoftimet push për një event të shtyhen për një kohë të shkurtër. Nëse ndodhin evente shtesë për të njëjtin person dhe për të njëjtën ticket ato do të grupohen në një mesazh të vetëm në vend që të dërgohen vec e vec..
        /// </summary>
        public static string ConsolidateNotifications_Description {
            get {
                return ResourceManager.GetString("ConsolidateNotifications_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivizuar.
        /// </summary>
        public static string ConsolidateNotifications_Prompt {
            get {
                return ResourceManager.GetString("ConsolidateNotifications_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervali i provimit të ridërgimit (minuta).
        /// </summary>
        public static string DeliveryAttemptInterval {
            get {
                return ResourceManager.GetString("DeliveryAttemptInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa shpesh duhet të kontrrollohet për njoftimet push që janë gati të dërgohen..
        /// </summary>
        public static string DeliveryAttemptInterval_Description {
            get {
                return ResourceManager.GetString("DeliveryAttemptInterval_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofruesit e dërgimit .
        /// </summary>
        public static string DeliveryProviders {
            get {
                return ResourceManager.GetString("DeliveryProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivizo SSL.
        /// </summary>
        public static string EnableSSL {
            get {
                return ResourceManager.GetString("EnableSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përjashtoni personat nga eventet e veta.
        /// </summary>
        public static string ExcludeSubscribersOwnEvents {
            get {
                return ResourceManager.GetString("ExcludeSubscribersOwnEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E REKOMANDUAR! Kjo parandalon që njoftimet push të dërgohen te i njëjti përdorues, veprimi i të cilit shkaktoi njoftimin..
        /// </summary>
        public static string ExcludeSubscribersOwnEvents_Description {
            get {
                return ResourceManager.GetString("ExcludeSubscribersOwnEvents_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përjashtoj.
        /// </summary>
        public static string ExcludeSubscribersOwnEvents_Prompt {
            get {
                return ResourceManager.GetString("ExcludeSubscribersOwnEvents_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nga adresa.
        /// </summary>
        public static string FromAddress {
            get {
                return ResourceManager.GetString("FromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa e email që do të përdoret kur dërgoni email nga ky ofrues.
        /// </summary>
        public static string FromAddress_Description {
            get {
                return ResourceManager.GetString("FromAddress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri nga cili dërgohet.
        /// </summary>
        public static string FromDisplayName {
            get {
                return ResourceManager.GetString("FromDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri që do shfaqet kur dërgohet email.
        /// </summary>
        public static string FromDisplayName_Description {
            get {
                return ResourceManager.GetString("FromDisplayName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravatar.
        /// </summary>
        public static string Gravatar {
            get {
                return ResourceManager.GetString("Gravatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivizon funksionin Gavatar të SendGrid ( ju duhet që të siguroheni që llogaria juaj e SendGrid të ketë të aktivizuar këtë funksion).
        /// </summary>
        public static string Gravatar_Description {
            get {
                return ResourceManager.GetString("Gravatar_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivizuar.
        /// </summary>
        public static string Gravatar_Prompt {
            get {
                return ResourceManager.GetString("Gravatar_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vonesa fillestare e konolidimit (minuta).
        /// </summary>
        public static string InitialConsolidationDelay {
            get {
                return ResourceManager.GetString("InitialConsolidationDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri fillestar i minutave për të pritur. Nëse ndodhin evente të reja për personin dhe ticket e njëjtë, sistemi do t&apos;i konsolidojë mesazhet në një njoftim të vetëm. Eventet e mëvonshme do të rrisin vonsën derisa të mos ndodhin ngjarje të mëtejshme, ose periudha maksimale e vonesës ka skaduar..
        /// </summary>
        public static string InitialConsolidationDelay_Description {
            get {
                return ResourceManager.GetString("InitialConsolidationDelay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndërprerja fillestare e ri provimi (minuta).
        /// </summary>
        public static string InitialRetryInterval {
            get {
                return ResourceManager.GetString("InitialRetryInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri i minutave për të pritur përpara përpjekjes së parë të provimit. Përpjekjet e ritheksuara të mëvonshme ndodhin në intervale të ngritura në numrin e përpjekjeve të përsëritura. Shembull: intervali = 2 dhe riprovimi = 3, përpjekja tjetër do të jetë në 8 minuta..
        /// </summary>
        public static string InitialRetryInterval_Description {
            get {
                return ResourceManager.GetString("InitialRetryInterval_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vonesa maksimale e konsolidimit (minuta).
        /// </summary>
        public static string MaximumConsolidationDelay {
            get {
                return ResourceManager.GetString("MaximumConsolidationDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimumi i kohës për të vonuar dërgimin e një njoftimi..
        /// </summary>
        public static string MaximumConsolidationDelay_Description {
            get {
                return ResourceManager.GetString("MaximumConsolidationDelay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Njoftimet janë aktivizuar.
        /// </summary>
        public static string NotificationsEnabled {
            get {
                return ResourceManager.GetString("NotificationsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivizuar.
        /// </summary>
        public static string NotificationsEnabled_Prompt {
            get {
                return ResourceManager.GetString("NotificationsEnabled_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri i tentativave për të riprovuar.
        /// </summary>
        public static string NumberOfRetryAttempts {
            get {
                return ResourceManager.GetString("NumberOfRetryAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kur gjërat shkojnë keq, kjo përcakton numrin e përpjekjeve që duhet të bëhen për të ridërguar njoftimin përpara se të shënohet si njoftim i dështuar..
        /// </summary>
        public static string NumberOfRetryAttempts_Description {
            get {
                return ResourceManager.GetString("NumberOfRetryAttempts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjurmimi i hapur.
        /// </summary>
        public static string OpenTracking {
            get {
                return ResourceManager.GetString("OpenTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivizon funksionin e gjurmimit të SendGrid.
        /// </summary>
        public static string OpenTracking_Description {
            get {
                return ResourceManager.GetString("OpenTracking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivizuar.
        /// </summary>
        public static string OpenTracking_Prompt {
            get {
                return ResourceManager.GetString("OpenTracking_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofruesit.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivizuar.
        /// </summary>
        public static string Provider_Prompt {
            get {
                return ResourceManager.GetString("Provider_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofruesi SendGrid (Email).
        /// </summary>
        public static string SendGridProvider {
            get {
                return ResourceManager.GetString("SendGridProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dërgo në Sink.
        /// </summary>
        public static string SendToSink {
            get {
                return ResourceManager.GetString("SendToSink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dërgon të gjitha emailet në adresën SendGrid sink (i dobishëm gjatë testimeve të dërgimit të emaile-ve për të parandaluar dërgimin e email tek një marrës i vërtetë).
        /// </summary>
        public static string SendToSink_Description {
            get {
                return ResourceManager.GetString("SendToSink_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivizuar.
        /// </summary>
        public static string SendToSink_Prompt {
            get {
                return ResourceManager.GetString("SendToSink_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP email nga.
        /// </summary>
        public static string SMTPFromAddress {
            get {
                return ResourceManager.GetString("SMTPFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa email që do të përdoret kur dërgoni email nga ky ofrues.
        /// </summary>
        public static string SMTPFromAddress_Description {
            get {
                return ResourceManager.GetString("SMTPFromAddress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP emri nga.
        /// </summary>
        public static string SMTPFromDisplayName {
            get {
                return ResourceManager.GetString("SMTPFromDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri që do të shfaqet kur dërgohet një email nga ky ofrues.
        /// </summary>
        public static string SMTPFromDisplayName_Description {
            get {
                return ResourceManager.GetString("SMTPFromDisplayName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Fjalëkalimi.
        /// </summary>
        public static string SMTPPassword {
            get {
                return ResourceManager.GetString("SMTPPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mund ta lini bosh në qoftë se idendifikimi nuk është i detyrueshëm.
        /// </summary>
        public static string SMTPPassword_Description {
            get {
                return ResourceManager.GetString("SMTPPassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Port.
        /// </summary>
        public static string SMTPPort {
            get {
                return ResourceManager.GetString("SMTPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP dërguesi (Emial).
        /// </summary>
        public static string SMTPProvider {
            get {
                return ResourceManager.GetString("SMTPProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP emri i serverit.
        /// </summary>
        public static string SMTPServerName {
            get {
                return ResourceManager.GetString("SMTPServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP përdoruesi.
        /// </summary>
        public static string SMTPUserName {
            get {
                return ResourceManager.GetString("SMTPUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mund ta lini bosh në qoftë se idendifikimi nuk është i detyrueshëm.
        /// </summary>
        public static string SMTPUserName_Description {
            get {
                return ResourceManager.GetString("SMTPUserName_Description", resourceCulture);
            }
        }
    }
}
