//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Localization.Views.PushNotificationSettings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index_sq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_sq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Localization.Views.PushNotificationSettings.Index-sq", typeof(Index_sq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cilësimet.
        /// </summary>
        public static string AntiNoise_Header {
            get {
                return ResourceManager.GetString("AntiNoise_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofruesit e shpërndarjes.
        /// </summary>
        public static string Delivery_Header {
            get {
                return ResourceManager.GetString("Delivery_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TicketDesk është në demo mode. Njoftimet push janë bllokuar.&lt;/p&gt;
        ///&lt;p&gt; Për të caktivizuar demo mode, ju lutem shkoni tek konfgurimet e sistemit.&lt;/p&gt;.
        /// </summary>
        public static string DemoMode_Alert {
            get {
                return ResourceManager.GetString("DemoMode_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cilësimet e përgjithshme.
        /// </summary>
        public static string General_Header {
            get {
                return ResourceManager.GetString("General_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cilësimet për njoftimet push.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të paktën një ofrues duhet të aktivizohet  në mënyrë që të dërgohen njoftimet..
        /// </summary>
        public static string RequiredProvider {
            get {
                return ResourceManager.GetString("RequiredProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruaj.
        /// </summary>
        public static string SaveOption {
            get {
                return ResourceManager.GetString("SaveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url e sistemit.
        /// </summary>
        public static string SiteRootUrl {
            get {
                return ResourceManager.GetString("SiteRootUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kjo është e vlefshme për tu siguruar që link-et që dërgohen në email përmbajnë url të saktë të sistemit..
        /// </summary>
        public static string SiteRootUrl_Help {
            get {
                return ResourceManager.GetString("SiteRootUrl_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url nuk është e saktë. Në qoftë se jeni duke e testuar lokalisht, specifiko IP adresen (http://127.0.0.1:80).
        /// </summary>
        public static string SiteRootUrl_Validation {
            get {
                return ResourceManager.GetString("SiteRootUrl_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cilësimet për njoftimet push.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdor URL aktuale.
        /// </summary>
        public static string UseCurrentURL {
            get {
                return ResourceManager.GetString("UseCurrentURL", resourceCulture);
            }
        }
    }
}
