//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Localization.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_sq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_sq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Localization.Domain.Strings-sq", typeof(Strings_sq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lejo përdoruesit të modifikojnë prioritetin?.
        /// </summary>
        public static string AllowInternalUsersToEditPriority {
            get {
                return ResourceManager.GetString("AllowInternalUsersToEditPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lejo përdoruesit të modifikojnë tags?.
        /// </summary>
        public static string AllowInternalUsersToEditTags {
            get {
                return ResourceManager.GetString("AllowInternalUsersToEditTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lejoni përdoruesit e brendshëm që ti caktojnë një personi një kërkesë (vetëm për krijimin e kërkesave të reja)?.
        /// </summary>
        public static string AllowInternalUsersToSetAssigned {
            get {
                return ResourceManager.GetString("AllowInternalUsersToSetAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lejoni përdoruesit e brendshëm të vendosin ose të ndryshojnë zotëruesin e ticket?.
        /// </summary>
        public static string AllowInternalUsersToSetOwner {
            get {
                return ResourceManager.GetString("AllowInternalUsersToSetOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: nga &quot;{1}&quot; te &quot;{2}&quot;.
        /// </summary>
        public static string Changes_From_To {
            get {
                return ResourceManager.GetString("Changes_From_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndryshime:.
        /// </summary>
        public static string Changes_Title {
            get {
                return ResourceManager.GetString("Changes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdoruesi nuk është i autorizuar për të kryer këtë veprim..
        /// </summary>
        public static string CheckSecurity_NotAuthorized {
            get {
                return ResourceManager.GetString("CheckSecurity_NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caktuar tek unë.
        /// </summary>
        public static string DefaultListNameAssignedToMe {
            get {
                return ResourceManager.GetString("DefaultListNameAssignedToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historiku i kërkesave.
        /// </summary>
        public static string DefaultListNameHistoryTickets {
            get {
                return ResourceManager.GetString("DefaultListNameHistoryTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërkesat e mia.
        /// </summary>
        public static string DefaultListNameMyTickets {
            get {
                return ResourceManager.GetString("DefaultListNameMyTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërkesat e hapura.
        /// </summary>
        public static string DefaultListNameOpenTickets {
            get {
                return ResourceManager.GetString("DefaultListNameOpenTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të pa caktuara.
        /// </summary>
        public static string DefaultListNameUnassigned {
            get {
                return ResourceManager.GetString("DefaultListNameUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roli i paracaktuar për rolet e reja.
        /// </summary>
        public static string DefaultNewUserRoles {
            get {
                return ResourceManager.GetString("DefaultNewUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdoruesi nuk është i autorizuar për të krijuar një kërkesë të re.
        /// </summary>
        public static string ExceptionSecurityUserCannotCreateNewTicket {
            get {
                return ResourceManager.GetString("ExceptionSecurityUserCannotCreateNewTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabim në konvertimin: nuk mund të konvertojmë emrin [{0}] tek specifikimi i tipit [{1}].
        /// </summary>
        public static string ExceptionSettingsTypeConversionError {
            get {
                return ResourceManager.GetString("ExceptionSettingsTypeConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përshkrimi.
        /// </summary>
        public static string Project_Description {
            get {
                return ResourceManager.GetString("Project_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri klientit.
        /// </summary>
        public static string Project_Name {
            get {
                return ResourceManager.GetString("Project_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoritë.
        /// </summary>
        public static string SelectList_Categories {
            get {
                return ResourceManager.GetString("SelectList_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritetet.
        /// </summary>
        public static string SelectList_Priorities {
            get {
                return ResourceManager.GetString("SelectList_Priorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipet e kërkesës.
        /// </summary>
        public static string SelectList_TicketTypes {
            get {
                return ResourceManager.GetString("SelectList_TicketTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përcakto.
        /// </summary>
        public static string TicketActivity_Assign {
            get {
                return ResourceManager.GetString("TicketActivity_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anullo më shumë info.
        /// </summary>
        public static string TicketActivity_CancelMoreInfo {
            get {
                return ResourceManager.GetString("TicketActivity_CancelMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbyll.
        /// </summary>
        public static string TicketActivity_Close {
            get {
                return ResourceManager.GetString("TicketActivity_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koment.
        /// </summary>
        public static string TicketActivity_Comment {
            get {
                return ResourceManager.GetString("TicketActivity_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krijo.
        /// </summary>
        public static string TicketActivity_Create {
            get {
                return ResourceManager.GetString("TicketActivity_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krijo.
        /// </summary>
        public static string TicketActivity_CreateOnBehalfOf {
            get {
                return ResourceManager.GetString("TicketActivity_CreateOnBehalfOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiko.
        /// </summary>
        public static string TicketActivity_Edit {
            get {
                return ResourceManager.GetString("TicketActivity_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiko dokumentat.
        /// </summary>
        public static string TicketActivity_EditAttachments {
            get {
                return ResourceManager.GetString("TicketActivity_EditAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbyll me forcë.
        /// </summary>
        public static string TicketActivity_ForceClose {
            get {
                return ResourceManager.GetString("TicketActivity_ForceClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dorëzohu.
        /// </summary>
        public static string TicketActivity_GiveUp {
            get {
                return ResourceManager.GetString("TicketActivity_GiveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaloje.
        /// </summary>
        public static string TicketActivity_Pass {
            get {
                return ResourceManager.GetString("TicketActivity_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofroni informacion.
        /// </summary>
        public static string TicketActivity_ProvideInfo {
            get {
                return ResourceManager.GetString("TicketActivity_ProvideInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricaktoje.
        /// </summary>
        public static string TicketActivity_ReAssign {
            get {
                return ResourceManager.GetString("TicketActivity_ReAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rihap.
        /// </summary>
        public static string TicketActivity_ReOpen {
            get {
                return ResourceManager.GetString("TicketActivity_ReOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërko më shumë informacion.
        /// </summary>
        public static string TicketActivity_RequestMoreInfo {
            get {
                return ResourceManager.GetString("TicketActivity_RequestMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U zgjidh.
        /// </summary>
        public static string TicketActivity_Resolve {
            get {
                return ResourceManager.GetString("TicketActivity_Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marr përsipër.
        /// </summary>
        public static string TicketActivity_TakeOver {
            get {
                return ResourceManager.GetString("TicketActivity_TakeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shtoni koment.
        /// </summary>
        public static string TicketActivityAddComment {
            get {
                return ResourceManager.GetString("TicketActivityAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to caktoni kërkesën tek {0}.
        /// </summary>
        public static string TicketActivityAssign {
            get {
                return ResourceManager.GetString("TicketActivityAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ka anulluar kërkesën për më shumë informacion.
        /// </summary>
        public static string TicketActivityCancelMoreInfo {
            get {
                return ResourceManager.GetString("TicketActivityCancelMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mbylli kërkesën.
        /// </summary>
        public static string TicketActivityClose {
            get {
                return ResourceManager.GetString("TicketActivityClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to krijoji kërkesën.
        /// </summary>
        public static string TicketActivityCreate {
            get {
                return ResourceManager.GetString("TicketActivityCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to krijoji kërkesën në emër të {0}.
        /// </summary>
        public static string TicketActivityCreateOnBehalfOf {
            get {
                return ResourceManager.GetString("TicketActivityCreateOnBehalfOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modifikoi kërkesën.
        /// </summary>
        public static string TicketActivityEditTicketInfo {
            get {
                return ResourceManager.GetString("TicketActivityEditTicketInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mbylli kërkesën me forcë.
        /// </summary>
        public static string TicketActivityForceClose {
            get {
                return ResourceManager.GetString("TicketActivityForceClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ka hequr dorë nga kërkesa.
        /// </summary>
        public static string TicketActivityGiveUp {
            get {
                return ResourceManager.GetString("TicketActivityGiveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modifikoi dokumentat e kërkesës.
        /// </summary>
        public static string TicketActivityModifyAttachments {
            get {
                return ResourceManager.GetString("TicketActivityModifyAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kaloi kërkesën tek {0}.
        /// </summary>
        public static string TicketActivityPass {
            get {
                return ResourceManager.GetString("TicketActivityPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to në prioritetin e {0}.
        /// </summary>
        public static string TicketActivityPriority {
            get {
                return ResourceManager.GetString("TicketActivityPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dhe riaktivizoi kërkesën..
        /// </summary>
        public static string TicketActivityReactivate {
            get {
                return ResourceManager.GetString("TicketActivityReactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ricaktoj kërkesën tek {0}.
        /// </summary>
        public static string TicketActivityReAssign {
            get {
                return ResourceManager.GetString("TicketActivityReAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rihapi kërkesën.
        /// </summary>
        public static string TicketActivityReOpen {
            get {
                return ResourceManager.GetString("TicketActivityReOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ka kërkuar më shumë informacion.
        /// </summary>
        public static string TicketActivityRequestMoreInfo {
            get {
                return ResourceManager.GetString("TicketActivityRequestMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zgjidhi kërkesën.
        /// </summary>
        public static string TicketActivityResolve {
            get {
                return ResourceManager.GetString("TicketActivityResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ka dhënë më shumë informacion.
        /// </summary>
        public static string TicketActivitySupplyMoreInfo {
            get {
                return ResourceManager.GetString("TicketActivitySupplyMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ka marrë kërkesën.
        /// </summary>
        public static string TicketActivityTakeOver {
            get {
                return ResourceManager.GetString("TicketActivityTakeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ka difekt.
        /// </summary>
        public static string TicketAffectsCustomer {
            get {
                return ResourceManager.GetString("TicketAffectsCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difekti.
        /// </summary>
        public static string TicketAffectsCustomerShort {
            get {
                return ResourceManager.GetString("TicketAffectsCustomerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caktuar për.
        /// </summary>
        public static string TicketAssignedTo {
            get {
                return ResourceManager.GetString("TicketAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caktuar.
        /// </summary>
        public static string TicketAssignedToShort {
            get {
                return ResourceManager.GetString("TicketAssignedToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        public static string TicketCategory {
            get {
                return ResourceManager.GetString("TicketCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        public static string TicketCategoryShort {
            get {
                return ResourceManager.GetString("TicketCategoryShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krijuar nga.
        /// </summary>
        public static string TicketCreatedBy {
            get {
                return ResourceManager.GetString("TicketCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krijuar nga.
        /// </summary>
        public static string TicketCreatedByShort {
            get {
                return ResourceManager.GetString("TicketCreatedByShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e krijimit.
        /// </summary>
        public static string TicketCreatedDate {
            get {
                return ResourceManager.GetString("TicketCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e krijimit.
        /// </summary>
        public static string TicketCreatedDateShort {
            get {
                return ResourceManager.GetString("TicketCreatedDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e statusit.
        /// </summary>
        public static string TicketCurrentStatusDate {
            get {
                return ResourceManager.GetString("TicketCurrentStatusDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e statusit.
        /// </summary>
        public static string TicketCurrentStatusDateShort {
            get {
                return ResourceManager.GetString("TicketCurrentStatusDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusi u vendos nga.
        /// </summary>
        public static string TicketCurrentStatusSetBy {
            get {
                return ResourceManager.GetString("TicketCurrentStatusSetBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusi u vendos nga.
        /// </summary>
        public static string TicketCurrentStatusSetByShort {
            get {
                return ResourceManager.GetString("TicketCurrentStatusSetByShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detajet.
        /// </summary>
        public static string TicketDetails {
            get {
                return ResourceManager.GetString("TicketDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detajet.
        /// </summary>
        public static string TicketDetailsShort {
            get {
                return ResourceManager.GetString("TicketDetailsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to është Html.
        /// </summary>
        public static string TicketIsHtml {
            get {
                return ResourceManager.GetString("TicketIsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to është Html.
        /// </summary>
        public static string TicketIsHtmlShort {
            get {
                return ResourceManager.GetString("TicketIsHtmlShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifikuar nga.
        /// </summary>
        public static string TicketLastUpdateBy {
            get {
                return ResourceManager.GetString("TicketLastUpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifikuar nga.
        /// </summary>
        public static string TicketLastUpdateByShort {
            get {
                return ResourceManager.GetString("TicketLastUpdateByShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifikuar në.
        /// </summary>
        public static string TicketLastUpdateDate {
            get {
                return ResourceManager.GetString("TicketLastUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifikuar në.
        /// </summary>
        public static string TicketLastUpdateDateShort {
            get {
                return ResourceManager.GetString("TicketLastUpdateDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zotëruesi.
        /// </summary>
        public static string TicketOwner {
            get {
                return ResourceManager.GetString("TicketOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zotëruesi.
        /// </summary>
        public static string TicketOwnerShort {
            get {
                return ResourceManager.GetString("TicketOwnerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioriteti.
        /// </summary>
        public static string TicketPriority {
            get {
                return ResourceManager.GetString("TicketPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioriteti.
        /// </summary>
        public static string TicketPriorityShort {
            get {
                return ResourceManager.GetString("TicketPriorityShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klienti.
        /// </summary>
        public static string TicketProject {
            get {
                return ResourceManager.GetString("TicketProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klienti.
        /// </summary>
        public static string TicketProjectShort {
            get {
                return ResourceManager.GetString("TicketProjectShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktive.
        /// </summary>
        public static string TicketStatusActive {
            get {
                return ResourceManager.GetString("TicketStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbyllur.
        /// </summary>
        public static string TicketStatusClosed {
            get {
                return ResourceManager.GetString("TicketStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Më shumë info.
        /// </summary>
        public static string TicketStatusMoreInfo {
            get {
                return ResourceManager.GetString("TicketStatusMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E zgjidhur.
        /// </summary>
        public static string TicketStatusResolved {
            get {
                return ResourceManager.GetString("TicketStatusResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TicketTagList {
            get {
                return ResourceManager.GetString("TicketTagList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TicketTagListShort {
            get {
                return ResourceManager.GetString("TicketTagListShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id e kërkesës.
        /// </summary>
        public static string TicketTicketId {
            get {
                return ResourceManager.GetString("TicketTicketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string TicketTicketIdShort {
            get {
                return ResourceManager.GetString("TicketTicketIdShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TicketTicketStatus {
            get {
                return ResourceManager.GetString("TicketTicketStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TicketTicketStatusShort {
            get {
                return ResourceManager.GetString("TicketTicketStatusShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipi.
        /// </summary>
        public static string TicketTicketType {
            get {
                return ResourceManager.GetString("TicketTicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipi.
        /// </summary>
        public static string TicketTicketTypeShort {
            get {
                return ResourceManager.GetString("TicketTicketTypeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri.
        /// </summary>
        public static string TicketTitle {
            get {
                return ResourceManager.GetString("TicketTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri.
        /// </summary>
        public static string TicketTitleShort {
            get {
                return ResourceManager.GetString("TicketTitleShort", resourceCulture);
            }
        }
    }
}
