//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Localization.Views.Ticket {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class New_sq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal New_sq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Localization.Views.Ticket.New-sq", typeof(New_sq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ka difekt.
        /// </summary>
        public static string AffectsCustomer {
            get {
                return ResourceManager.GetString("AffectsCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TicketDesk është në demo mode. Bashkëngjitja e dokumentave është e bllokuar.&lt;/p&gt;.
        /// </summary>
        public static string Attachment_Demo_Alert {
            get {
                return ResourceManager.GetString("Attachment_Demo_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidh dokumentin këtu ose kliko për të zgjedhur..
        /// </summary>
        public static string Attachment_Instructions {
            get {
                return ResourceManager.GetString("Attachment_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kthehu tek lista.
        /// </summary>
        public static string BackOption {
            get {
                return ResourceManager.GetString("BackOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detajet.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiko.
        /// </summary>
        public static string EditOption {
            get {
                return ResourceManager.GetString("EditOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E pazgjedhur.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentat.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezencë fizike.
        /// </summary>
        public static string HardwareSupport {
            get {
                return ResourceManager.GetString("HardwareSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krijo një kërkesë të re.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string OnlineSupport {
            get {
                return ResourceManager.GetString("OnlineSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parashiko.
        /// </summary>
        public static string PreviewOption {
            get {
                return ResourceManager.GetString("PreviewOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krijo.
        /// </summary>
        public static string SaveOption {
            get {
                return ResourceManager.GetString("SaveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulli i kërkesës.
        /// </summary>
        public static string TicketTitle_Placeholder {
            get {
                return ResourceManager.GetString("TicketTitle_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërkesë e re.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E zgjedhur.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuk mund ta krijojme këtë kërkesë. Ju lutem kontrrolloni gabimet më poshtë.
        /// </summary>
        public static string UnableCreateTicket {
            get {
                return ResourceManager.GetString("UnableCreateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me mjetin e ArfaNet.
        /// </summary>
        public static string WithArfaNetAuto {
            get {
                return ResourceManager.GetString("WithArfaNetAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me mjet personal.
        /// </summary>
        public static string WithPersonalAuto {
            get {
                return ResourceManager.GetString("WithPersonalAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me ndihmes teknik.
        /// </summary>
        public static string WithSupport {
            get {
                return ResourceManager.GetString("WithSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditët e punës.
        /// </summary>
        public static string WorkingDays_Placeholder {
            get {
                return ResourceManager.GetString("WorkingDays_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orët e punës.
        /// </summary>
        public static string WorkingHours_Placeholder {
            get {
                return ResourceManager.GetString("WorkingHours_Placeholder", resourceCulture);
            }
        }
    }
}
