//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Localization.Views.TicketActivity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_sq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_sq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Localization.Views.TicketActivity.Strings-sq", typeof(Strings_sq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ka difekt.
        /// </summary>
        public static string AffectsCustomer_Label {
            get {
                return ResourceManager.GetString("AffectsCustomer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TicketDesk është në demo mode. Bashkëngjitja e dokumentave është e bllokuar.&lt;/p&gt;.
        /// </summary>
        public static string Attachment_Demo_Alert {
            get {
                return ResourceManager.GetString("Attachment_Demo_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidh dokumentin këtu ose kliko për të zgjedhur..
        /// </summary>
        public static string Attachment_Instructions {
            get {
                return ResourceManager.GetString("Attachment_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentat.
        /// </summary>
        public static string Attachments_Label {
            get {
                return ResourceManager.GetString("Attachments_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiko.
        /// </summary>
        public static string Comment_EditOption {
            get {
                return ResourceManager.GetString("Comment_EditOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koment.
        /// </summary>
        public static string Comment_Label {
            get {
                return ResourceManager.GetString("Comment_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parashiko.
        /// </summary>
        public static string Comment_PreviewOption {
            get {
                return ResourceManager.GetString("Comment_PreviewOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiko.
        /// </summary>
        public static string Details_EditOption {
            get {
                return ResourceManager.GetString("Details_EditOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detajet.
        /// </summary>
        public static string Details_Label {
            get {
                return ResourceManager.GetString("Details_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parashiko.
        /// </summary>
        public static string Details_PreviewOption {
            get {
                return ResourceManager.GetString("Details_PreviewOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anullo.
        /// </summary>
        public static string Form_CancelOption {
            get {
                return ResourceManager.GetString("Form_CancelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulli i kërkesës.
        /// </summary>
        public static string Form_TicketTitle_Placeholder {
            get {
                return ResourceManager.GetString("Form_TicketTitle_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caktuar për mua?.
        /// </summary>
        public static string ReOpen_AssignToMe {
            get {
                return ResourceManager.GetString("ReOpen_AssignToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgjidh këtë box për të caktuar këtë kërkesë tek vetja tani. Në qoftë se nuk zgjidhet, kërkesa do të rihapet si e papërcaktuar..
        /// </summary>
        public static string ReOpen_Instructions {
            get {
                return ResourceManager.GetString("ReOpen_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ReOpen_Label {
            get {
                return ResourceManager.GetString("ReOpen_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck këtë për të dhënë informacion pa ndryshuar statusin e kërkesës..
        /// </summary>
        public static string SupplyMoreInfo_Instructions {
            get {
                return ResourceManager.GetString("SupplyMoreInfo_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SupplyMoreInfo_Label {
            get {
                return ResourceManager.GetString("SupplyMoreInfo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riaktivizo kërkesën.
        /// </summary>
        public static string SupplyMoreInfo_ReactivateTicket {
            get {
                return ResourceManager.GetString("SupplyMoreInfo_ReactivateTicket", resourceCulture);
            }
        }
    }
}
