//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Localization.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_sq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_sq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Localization.Models.Strings-sq", typeof(Strings_sq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- asnjë --.
        /// </summary>
        public static string AssignedTo_Anyone {
            get {
                return ResourceManager.GetString("AssignedTo_Anyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- pa përcaktuar --.
        /// </summary>
        public static string AssignedTo_Unassigned {
            get {
                return ResourceManager.GetString("AssignedTo_Unassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi dhe konfirmimi i fjalëkalimit nuk përputhen..
        /// </summary>
        public static string ConfirmationDoNotMatch {
            get {
                return ResourceManager.GetString("ConfirmationDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmo fjalëkalimin e ri.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmo fjalëkalimin.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi aktual.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled_Prompt {
            get {
                return ResourceManager.GetString("Disabled_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri i plotë.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përcakton nëse llogaria është caktivizuar nga një administrator..
        /// </summary>
        public static string IsDisabled_Description {
            get {
                return ResourceManager.GetString("IsDisabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përcakton nëse një llogari është bllokuar. Bllokimet e përkohshme krijohen nga përpjekjet e pavlefshme për tu futur në sistem..
        /// </summary>
        public static string IsLocked_Description {
            get {
                return ResourceManager.GetString("IsLocked_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I bllokuar.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I bllokuar.
        /// </summary>
        public static string Locked_Prompt {
            get {
                return ResourceManager.GetString("Locked_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi i ri dhe konfirmimi fjalëkalimit nuk përputhen..
        /// </summary>
        public static string NewConfirmationDoNotMatch {
            get {
                return ResourceManager.GetString("NewConfirmationDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi i ri.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Më mbaj mend?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- zgjidh --.
        /// </summary>
        public static string SelectList_DefaultItem {
            get {
                return ResourceManager.GetString("SelectList_DefaultItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktive.
        /// </summary>
        public static string TicketStatus_Active {
            get {
                return ResourceManager.GetString("TicketStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- asnjë --.
        /// </summary>
        public static string TicketStatus_Any {
            get {
                return ResourceManager.GetString("TicketStatus_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I mbyllur.
        /// </summary>
        public static string TicketStatus_Closed {
            get {
                return ResourceManager.GetString("TicketStatus_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Më shumë informacion.
        /// </summary>
        public static string TicketStatus_MoreInfo {
            get {
                return ResourceManager.GetString("TicketStatus_MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- i hapur --.
        /// </summary>
        public static string TicketStatus_Open {
            get {
                return ResourceManager.GetString("TicketStatus_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U zgjidh.
        /// </summary>
        public static string TicketStatus_Resolved {
            get {
                return ResourceManager.GetString("TicketStatus_Resolved", resourceCulture);
            }
        }
    }
}
