// <auto-generated />
namespace TicketDesk.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _added_OnlineSupport_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_added_OnlineSupport_column));
        
        string IMigrationMetadata.Id
        {
            get { return "202009110920458__added_OnlineSupport_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
