//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Localization.Views.UserAdministration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Edit_sq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Edit_sq() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Localization.Views.UserAdministration.Edit-sq", typeof(Edit_sq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administratorët.
        /// </summary>
        public static string Administrators {
            get {
                return ResourceManager.GetString("Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdoruesit që do të menaxhojnë cilësimet e TicketDesk dhe mund të menaxhojnë llogaritë e përdoruesve dhe të drejtat. Ky rol gjithashtu përfshin të gjitha të drejtat nga Help Desk Staf dhe Përdoruesit e jashtëm..
        /// </summary>
        public static string Administrators_Description {
            get {
                return ResourceManager.GetString("Administrators_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ktheu tek përdoruesit.
        /// </summary>
        public static string BackOption {
            get {
                return ResourceManager.GetString("BackOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detajet e llogarisë.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Desk Staf.
        /// </summary>
        public static string HelpDeskStaff {
            get {
                return ResourceManager.GetString("HelpDeskStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdoruesit të cilëve u caktohen kërkesa. Ky rol ka akses në grupin e plotë të aktiviteteve te kërkesave. Gjithashtu ky rol përfshin edhe të drejtat për rolin e përdoruesve të brendshëm..
        /// </summary>
        public static string HelpDeskStaff_Description {
            get {
                return ResourceManager.GetString("HelpDeskStaff_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdoruesit e brendshëm.
        /// </summary>
        public static string InternalUsers {
            get {
                return ResourceManager.GetString("InternalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ky rol është për përdoruesit fundorë. Ata mund të dërgojnë kërkesa, mund të vendosen si zotërues të një kërkese dhe mund të kryejnë një sërë veprimesh të kufizuara në kërkesat që zotërojnë..
        /// </summary>
        public static string InternalUsers_Description {
            get {
                return ResourceManager.GetString("InternalUsers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menaxho llogarinë e përdoruesit.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Në pritje të miratimit.
        /// </summary>
        public static string PendingApproval {
            get {
                return ResourceManager.GetString("PendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nëse nuk është konfiguruar ndryshe në cilësimet e sistemit, ky rol është roli që i përcaktohet automatikisht përdoruesve gjatë regjistrimit. Ky rol nuk ka asnjë të drejtë brenda TicketDesk. Është menduar si një shënues për të ndihmuar administratorët të gjejnë më lehtë llogaritë e reja dhe ti përcaktojnë një rol të ri..
        /// </summary>
        public static string PendingApproval_Description {
            get {
                return ResourceManager.GetString("PendingApproval_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruaj.
        /// </summary>
        public static string SaveOption {
            get {
                return ResourceManager.GetString("SaveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shfaq përshkrimet e roleve.
        /// </summary>
        public static string ShowRoleDescriptions {
            get {
                return ResourceManager.GetString("ShowRoleDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiko llogarinë e përdoruesit.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
